language: python

cache: pip

python:
  - "3.5"

os: linux

dist: xenial

services:
  - xvfb

sudo: required

git:
  depth: 1

before_install:
  # install and run pep8 and docstyle tests
  - pip install pydocstyle
  - pydocstyle --convention numpy
  - pip install flake8
  - flake8 --version
  - flake8 --show-source

  # Setup conda (needed for opencv, ray dependency)
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - export TEST_FLAG="True"
  - conda config --append channels https://repo.anaconda.com/pkgs/free
  - conda config --append channels https://repo.anaconda.com/pkgs/pro

  # Requirements for stable baselines
  - sudo apt-get update && sudo apt-get install cmake libopenmpi-dev python3-dev zlib1g-dev

  # Set up requirements for flow
  - conda env create -f environment.yml
  - source activate flow

  # [sumo] dependencies and binaries
  - pushd $HOME/build/flow-project
  -     ./flow/scripts/setup_sumo_ubuntu1604.sh
  - popd
  - source ~/.bashrc

  # [aimsun] install the conda env and update the path to the env
  - pushd $HOME/build/flow-project
  -     ./flow/scripts/setup_aimsun.sh
  - popd
  - source ~/.bashrc
  - export AIMSUN_SITEPACKAGES="/home/travis/miniconda/envs/aimsun_flow"
  - export AIMSUN_NEXT_PATH="/home/user/Aimsun_Next_XXX"

  # Install stable-baselines
  - pip install stable_baselines==2.7.0

  # Install h-baselines
  - pushd $HOME
  - git clone https://github.com/AboudyKreidieh/h-baselines.git
  - pushd h-baselines
  - pip install -e .
  - popd
  - popd

  - ls ../

install:
  - sudo apt update
  - sudo apt install -y freeglut3-dev libgl1-mesa-dev libglu1-mesa-dev
  - pip install -e .
  - pip install coveralls
  - pip install jupyter

script:
  - nose2 --with-coverage

after_success:
  - coveralls
